import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class P5 extends Application
{

    public static void main(String[] args)
    {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception
    {
        Group g = new Group();
        Label label = new Label("Blyat");
        g.getChildren().add(label);                
        Scene scene = new Scene(g, 400, 400);
        primaryStage.setTitle("Liveshare: An epic.");
        primaryStage.setScene(scene);
        primaryStage.show();                                                                   
    }
}
